version: "3.7"

services:

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Sql__ConnectionString: Server=sql.data;Database=FamilyGuy;User Id=sa;Password=P@ssw0rd123
      Jwt__Key: super_secret_key_123!
      Jwt__Issuer: http://localhost:8080
      Jwt__ExpiryMinutes: 180
      Host__Url: http://localhost:8080
    ports:
      - 8080:80
    networks:
      - dev

  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssw0rd123
    ports:
      - 5433:1433
    networks:
      - dev

networks:
  dev:
    driver: bridge
